name: Pull Requests

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw -B -ntp clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          if-no-files-found: error

      - name: Deploy (placeholder)
        run: |
          echo "Deploy step placeholder. Add your deployment commands or actions here."
